AWSTemplateFormatVersion: '2010-09-09'
Description: Aplicação Spring Boot com EC2

Resources:
  SpringAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  SpringAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-058a8a5ab36292159 # AMI Amazon Linux 2 - us-east-1
      KeyName: minha-chave-ec2       # Nome da chave PEM que você enviou
      SecurityGroups:
        - !Ref SpringAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-1.8.0-openjdk
          aws s3 cp s3://bucketspringaws/demo-0.0.1-SNAPSHOT.jar /home/ec2-user/
          cd /home/ec2-user/
          nohup java -jar demo-0.0.1-SNAPSHOT.jar > /home/ec2-user/log.txt 2>&1 &
          # Verifica se o Java está rodando e salva o estado dos processos em java_process.txt
          ps aux | grep java > /home/ec2-user/java_process.txt
          # Exibe os últimos 10 logs da aplicação
          tail -n 10 /home/ec2-user/log.txt
